export const BOSS_DEATH_GRAY_IN_MS = 150;
export const BOSS_DEATH_FALL_START_MS = 600;
export const BOSS_DEATH_FALL_DURATION_MS = 520;
export const BOSS_DEATH_IMPACT_MS = BOSS_DEATH_FALL_START_MS + BOSS_DEATH_FALL_DURATION_MS;
export const BOSS_DEATH_FADE_START_MS = 1180;
export const BOSS_DEATH_MS = 2080;
