import * as THREE from 'three';
import { expect, it, vi } from 'vitest';
import { HeavyHitFeedback, SURVIVING_HIT_STYLES } from '../src/rendering/enemies/HeavyHitFeedback';
import { GiantRenderer } from '../src/rendering/enemies/GiantRenderer';
import { createChibiGiantFamily } from '../src/rendering/enemies/ChibiThreatFamilies';
import { ART } from '../src/art/ArtDirection';
import { giantDeathPose } from '../src/presentation/GiantDrama';

it('uses a soft Giant style without leaking intensity to Heavy or allocating materials per hit', () => {
  const scene=new THREE.Scene(), feedback=new HeavyHitFeedback(scene);
  const enemy={ id:1,tier:1,archetype:'giant' as const,x:0,z:15,hp:100 };
  feedback.observe(enemy,0); feedback.observe({...enemy,id:2,archetype:'heavy'},0);
  feedback.update(new Set([1,2]),0);
  const bodies=scene.children.filter(child=>child.name==='heavy-hit-body') as THREE.Mesh<THREE.BufferGeometry,THREE.MeshBasicMaterial>[];
  const sparks=scene.children.filter(child=>child.name==='heavy-hit-sparks');
  expect(bodies[0].material.color.getHexString()).toBe('dda999');
  expect(bodies[0].material.opacity).toBe(.24);
  expect(bodies[1].material.opacity).toBe(.72);
  expect(bodies[1].material.color.getHexString()).toBe(new THREE.Color(ART.fx.core).getHexString());
  expect(sparks[0].children.filter(child=>child.visible)).toHaveLength(3);
  expect(sparks[1].children.filter(child=>child.visible)).toHaveLength(4);
  const spark=sparks[0].children[0] as THREE.Mesh<THREE.BufferGeometry,THREE.MeshBasicMaterial>;
  expect(spark.scale.x).toBe(.9); expect(spark.material.opacity).toBe(.5);
  feedback.update(new Set([1,2]),50);
  expect(bodies[0].visible).toBe(true);
  expect(spark.material.opacity).toBeCloseTo(.5*(1-50/170));
  feedback.update(new Set([1,2]),100); expect(bodies[0].visible).toBe(false);
  feedback.update(new Set([1,2]),170); expect(sparks[0].visible).toBe(false);
  const material=bodies[0].material, disposed=vi.spyOn(material,'dispose');
  expect(feedback.observe(enemy,250)).toBe(true);
  expect(scene.children).toHaveLength(4); expect(bodies[0].material).toBe(material);
  const borrowed=new THREE.BufferGeometry(), borrowedDisposed=vi.spyOn(borrowed,'dispose');
  feedback.setBody(1,borrowed,new THREE.Matrix4(),250);
  feedback.dispose(); expect(disposed).toHaveBeenCalledTimes(1); expect(borrowedDisposed).not.toHaveBeenCalled();
  borrowed.dispose();
});

it('limits ordinary emissive while preserving Giant reveal, lethal flash and dedicated HP dimensions', () => {
  const scene=new THREE.Scene(), family=createChibiGiantFamily(), renderer=new GiantRenderer(scene,family);
  const feedback=new HeavyHitFeedback(scene);
  const enemy={id:1,tier:1,archetype:'giant' as const,x:0,z:10,hp:100,visualScale:3};
  renderer.update(enemy,0,feedback);
  expect(renderer.barVisible(0)).toBe(false); expect(renderer.barVisible(1500)).toBe(true);
  feedback.observe(enemy,2000); renderer.update(enemy,2000,feedback);
  const body=scene.getObjectByName('giant-body') as THREE.Mesh<THREE.BufferGeometry,THREE.MeshStandardMaterial>;
  expect(body.material.emissiveIntensity).toBe(SURVIVING_HIT_STYLES.giant.emissivePeak);
  expect(body.material.emissiveIntensity).toBeLessThanOrEqual(.12);
  expect(body.material.emissive.getHexString()).toBe('dda999');
  const bar=renderer.healthBarLayout(enemy); expect(bar.width).toBeCloseTo(3.6); expect(bar.height).toBeCloseTo(.6);
  renderer.die(enemy,2100); renderer.update(undefined,2110,feedback);
  expect(body.material.emissive.getHexString()).toBe(new THREE.Color(ART.fx.core).getHexString());
  expect(body.material.emissiveIntensity).toBeCloseTo(giantDeathPose(10).lethalFlash*.6);
  renderer.dispose(); feedback.dispose(); family.dispose();
});
