import { z } from 'zod';

// Temporary lane experiment, separate from the retained tier/Boss balance.
export const CatharsisConfigSchema = z.strictObject({
  progression: z.strictObject({
    xpRequirements: z.array(z.number().int().positive()).min(1).default([28, 60, 110, 180, 280, 420]),
    xpFallbackMultiplier: z.number().finite().gt(1).default(1.45),
    gruntKillXp: z.number().int().nonnegative().default(1),
    heavyKillXp: z.number().int().nonnegative().default(10),
    fireRatePerLevel: z.number().finite().nonnegative().default(1),
    fireRateTaperStartLevel: z.number().int().min(2).default(5),
    fireRateTaperFirstGain: z.number().finite().nonnegative().default(.5),
    fireRateTaperDecay: z.number().finite().min(0).lt(1).default(.8),
  }).default({ xpRequirements: [28, 60, 110, 180, 280, 420], xpFallbackMultiplier: 1.45, gruntKillXp: 1, heavyKillXp: 10, fireRatePerLevel: 1, fireRateTaperStartLevel: 5, fireRateTaperFirstGain: .5, fireRateTaperDecay: .8 }),
  pressureMultipliers: z.array(z.number().finite().min(1).max(4)).min(1).default([1, 1, 1, 1, 1.25, 1.35, 1.45, 1.55, 1.6, 1.65]),
  giant: z.strictObject({
    enabled: z.boolean().default(false),
    unlockLevel: z.number().int().min(6).default(6),
    introDelaySeconds: z.number().finite().nonnegative().default(4),
    hp: z.number().finite().positive().default(28),
    xp: z.number().int().nonnegative().default(30),
    speed: z.number().finite().nonnegative().default(.08),
    visualScale: z.number().finite().min(2).max(3).default(2.4),
    widthMultiplier: z.number().finite().positive().default(.85),
    gaitCycleMs: z.number().finite().positive().default(850),
  }).default({ enabled: false, unlockLevel: 6, introDelaySeconds: 4, hp: 28, xp: 30,
    speed: .08, visualScale: 2.4, widthMultiplier: .85, gaitCycleMs: 850 }),
  heavyFrontClearance: z.number().finite().nonnegative().default(2.5),
  defenseMode: z.boolean().default(false),
  defenseSpawnAheadDistance: z.number().finite().positive().default(53),
  crowdDepthSpan: z.number().finite().positive().default(5),
  laneSwitchSeconds: z.number().finite().positive().default(.15),
  lateralSpreadFraction: z.number().finite().min(0).max(.45).default(.26),
  memberDepthSpacing: z.number().finite().positive().default(.85),
  depthJitter: z.number().finite().nonnegative().default(.35),
  laneCount: z.number().int().min(3).max(16),
  edgeInset: z.number().finite().positive(),
  waveRows: z.number().int().min(2),
  priorityWaves: z.number().int().min(1).max(10),
  // Absent in older snapshots: retain their one/two-front composition path.
  pressureLaneCount: z.number().int().min(1).max(16).optional(),
  groupSize: z.number().int().min(1).max(100),
  groupRowStride: z.number().int().positive(),
  secondLaneChance: z.number().min(0).max(1),
  heavyChance: z.number().min(0).max(1),
  gruntSpeed: z.number().finite().nonnegative(),
  heavySpeed: z.number().finite().nonnegative(),
  heavyHp: z.number().finite().gt(1),
  enemyVisualScale: z.number().finite().positive(),
  heavyVisualScale: z.number().finite().gt(1),
  heavyWidthMultiplier: z.number().finite().positive().max(2).default(1),
  heavyHeightMultiplier: z.number().finite().positive().max(2).default(1),
  heavyDepthMultiplier: z.number().finite().positive().max(2).default(1),
  rewardAimRadius: z.number().finite().positive(),
}).refine((value) => value.defenseMode || (value.groupSize - 1) * value.groupRowStride < value.waveRows,
  { message: 'Group must fit inside one wave' })
  .refine(value => value.pressureLaneCount === undefined || value.pressureLaneCount <= value.laneCount,
    { message: 'Pressure lane count must fit inside the battlefield' });

export type CatharsisConfig = z.infer<typeof CatharsisConfigSchema>;
